### ISSUE TITLE
3.3.3.3 - Pantalla de detalle de usuario solicitante

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#100]
Incluir los datos personales como nombre, teléfono, mail (no incluir la ubicación).
Utilizar la foto del slide menu como foto para el header del detalle.
Se debe agregar un botón para aceptar o rechazar la solicitud de adopción del usuario en cuestión. Solicitar confirmación al rechazar/aceptar

**Comment by nicodiaz55** [comment]
Solo falta pasar estos datos vía base de datos o desde la activity anterior.
- [x] Cargar los datos en la activity de la mascota seleccionada actual (en SolicitarAdopcionActivity.java)
