### ISSUE TITLE
3.3.3.4 - Servicio para aceptar o rechazar una solicitud de adopcion

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#101]
Se debe poder rechazar algunas solicitudes de adopción. 
Cuando se acepta una solicitud se deben rechazar automáticamente todas las demás (no rechazadas)

**Comment by nicodiaz55** [comment]
Según lo conversado, la idea es que las solicitudes se puedan marcar con un estado tipo "ACEPTADA" o "RECHAZADA" (y un "PENDIENTE" o algo similar). Al marcarlas como "RECHAZADA", no se deben listar en el listado. Al marcar una como "ACEPTADA", se debe marcar todas las demas como "RECHAZADA".

Cualquiera que haya mandado una solicitud a esta mascota no podrá enviar una nueva. Si le rechazaron la adopcion, por algo es (?). Solo podrá reenviar si el dueño la vuelve a subir (ponele, en caso que aceptó una adopcion pero salió mal y la vuelve a subir).

**Comment by nicodiaz55** [comment]
A definir: que pasa cuando acepto una solicitud. ¿Otros usuarios pueden seguir mandando solicitudes de adopcion por mas que ya acepté otra? (Quedan como pendientes). Por ahora eso SI se puede. Hablar con el cliente.
