### ISSUE TITLE
0 - Testing

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#108]
Hacer testing general. Incluye hacer mockups para los servicios externos (ej. Facebook)

Info:
http://www.vogella.com/tutorials/AndroidTesting/article.html
https://developer.android.com/tools/testing/index.html
https://developer.android.com/training/activity-testing/activity-unit-testing.html
http://developer.android.com/tools/testing/testing_android.html

**Comment by nicodiaz55** [comment]
Agregar test de regex de youtube.

**Comment by jennywoites** [comment]
Testing unitario finalizado. Verificar registros de pruebas en drive: https://drive.google.com/drive/folders/0B5nlhJWBoNrXYzBkUXlzUzhfc00
