### ISSUE TITLE
Cambiar título de agregar mascota

### ISSUE THREAD

**Issue by nicodiaz55** [jennywoites/TallerProyectosII-2C-2015#122]
En el título del modal que se abre cuando quiero publicar una nueva mascota en adopción debería decir : Publicar mascota en adopción.

Lo mismo en Perdidas.

**Comment by jennywoites** [comment]
El título "Publicar mascota en adopción" es demasiado largo y según material design no se usan multiples lineas para los títulos. Se utiliza un título que indique que se publica una adopción/ una pérdida, dejando que se sobreentienda que la publicación es de una mascota.
"Publicar una adopción" / "Publicar una pérdida"
