### ISSUE TITLE
Campos obligatorios no deben utilizar asterisco

### ISSUE THREAD

**Issue by nicodiaz55** [jennywoites/TallerProyectosII-2C-2015#127]
Investigar que se usa en Material Design y aplicarlo.

**Comment by jennywoites** [comment]
Lo de agregar los asteriscos lo pusimos porque en la demo nos habían comentado que era mejor marcarlos porque sino el usuario no sabe qué campos son obligatorios hasta que no presiona enviar y ve que se le marcan los campos que dejé en blanco y eran obligatorios, ya los sacamos. Por lo que vimos, no se suelen marcar directamente a menos que hayan quedado incompletos, te gustaría que se marquen desde antes de alguna otra manera que no sea asteriscos?

Claro. Sé que les comentaron eso pero como ustedes están usando material me pareció bueno comentarles esto. En las guias dice que en principio sólo habría que pedir información útil, si llegara a existir la necesidad de ingresar información opcional, es mejor indicar que ese campo específicamente es opcional (a veces se lo suele expresar con placeholders.

**Comment by jennywoites** [comment]
Solo quitar los asteriscos. No agregar nada más.
Los opcionales no se los hace con placeholders ya que usamos un texto por default que será el título que se eleva después en el campo por lo que no tiene sentido ponerlo con eso.
