### ISSUE TITLE
Filtrado por distancia a partir de la ubicación actual (para Perdidos)

### ISSUE THREAD

**Issue by nicodiaz55** [jennywoites/TallerProyectosII-2C-2015#128]
Si el usuario tiene el GPS activado, se debe utilizar esa posición ACTUAL para calcular el filtro por distancia a una mascota perdida. Si lo tiene desactivado, utilizar la ubicación del perfil del usuario.

**Comment by jennywoites** [comment]
Desestimada por el cliente
