### ISSUE TITLE
3.3.5.2 - Despublicaciones automáticas

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#131]
- Se despublica automáticamente al mes de publicada inicialmente y no adoptada.
- Todas las mascotas publicadas se borran al año de la publicación inicial. Se eliminan también de la base de datos las solicitudes de adopción y los comentarios correspondientes.

Verificar si se puede hacer de forma automática por Parse. Sino llamar a un servicio que se encargue de cambiar el estado ("Cancelada") a todas las filas con la fecha que corresponda y cuyo estado sea "En Adopción". Este servicio debería ser llamado cuando se quiere entrar a la pantalla de Adopciones y a la pantalla de Mis Mascotas.
Análogo pero que en lugar de cambiar el estado elimine los datos de la bdd

**Comment by juanmanuelromeraferrio** [comment]
Falta esto Se despublica automáticamente al mes de publicada inicialmente y no adoptada.
