### ISSUE TITLE
Despublicar mascota - Bloquear comentarios/solicitudes

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#172]
Cuando despublico una mascota la push notification me lleva a la pantalla de detalle de mascota pero sigo teniendo habilitados los comentarios.
Pasa lo mismo con la habilitación cuando lo hago desde una pantalla no actualizada. Puedo ver el detalle y la query se envia igualmente.
También pasa cuando la despublico y soy el dueño que puedo seguir comentando

**Comment by ramirodoi** [comment]
Desestimado
