### ISSUE TITLE
Modificar detalle mascota

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#185]
Agregar el msj de "necesita hogar de tránsito" Agregar dentro del menú la opción "ofrecer tránsito" se debe enviar mail al usuario dueño con los datos del solicitante

**Comment by nicodiaz55** [comment]
- [x] Agregar el msj de "necesita hogar de tránsito".
- [x] Agregar dentro del menú la opción "ofrecer tránsito".
- [ ] Se debe enviar mail al usuario dueño con los datos del solicitante.
