### ISSUE TITLE
Denunciar comentario

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#186]
Agregar botón al comentario para poder denunciar. Agregar los servicios para denunciar. Modificar lo visual para que los comentarios bloqueados (o de usuarios bloqueados) no se muestren. Modificar el servicio que trae los comentarios. Pantalla de selección de motivo

**Comment by nicodiaz55** [comment]
- [x] Agregar botón al comentario para poder denunciar.
- [ ] Agregar los servicios para denunciar.
- [x] Modificar lo visual para que los comentarios bloqueados (o de usuarios bloqueados)  no se muestren.
- [x] Modificar el servicio que trae los comentarios.
- [x] Pantalla de selección de motivo

**Comment by nicodiaz55** [comment]
Tabla en parse terminada.
