### ISSUE TITLE
Pantalla ranking de denuncias

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#194]
Mostrar tabla con header usuario denunciado, cantidad de publicaciones, cantidad de comentarios denunciados y botón bloquear usuario. Agregar servicios para modificar usuario, publicaciones, comentarios,  solicitudes BD y denuncias

**Comment by jennywoites** [comment]
Se resolvió de otra manera. Se ordena la tabla de bloquear/desbloquear usuarios y se muestran allí la cantidad de denuncias
