### ISSUE TITLE
(10) Adopción Nueva - Lógica para redimensionar imágenes

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#36]

**Comment by nicodiaz55** [comment]
Voy a investigar un cacho de esto, probaré aparte las funciones y cuando vea que tengo algo funcionando lo commiteo.

**Comment by nicodiaz55** [comment]
Actualmente, cargar imagenes grandes puede ocacionar dos cosas: que la app se cierre (seguramente por falta de memoria) o que pareciera no cargarla en la vista previa que se muestra en el Nueva Adopción. (Esto a futuro también ocurrirá en publicar mascota perdida y encontrada)
