### ISSUE TITLE
Cerrar Sesión - No funciona iniciar luego de cerrar sesión

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#51]
Al cerrar sesión ya no vuelve a funcionar el inicio con facebook

Para loguearse otra vez hay que matar la aplicación y volver a cargarla

(solo pasa cuando quiero volver a iniciar sesión cuando tengo ya iniciada la app: Si la cierro con la sesión iniciada, la vuelvo a abrir y cierro la sesión si me puedo volver a logguear)

**Comment by juanmanuelromeraferrio** [comment]
No se puede reproducir.
