### ISSUE TITLE
Adopción de Mascotas - No trae todas las mascotas en la BD

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#55]
Al añadir la mascota, se agrega a la bdd pero no se está trayendo a la app en la búsqueda (probamos al hacer click en agregar, al recargar adopciones y cerrando y volviendo a abrir la app)

**Comment by nicodiaz55** [comment]
Hubo un commit que decía que no se iban a  mostrar las que pertenecen al mismo usuario. Hay que cambiar eso.

**Comment by juanmanuelromeraferrio** [comment]
Esto se hizo porque no tiene sentido que si yo subí una mascota yo después pueda adoptarla.

**Comment by jennywoites** [comment]
Más adelante se puede hacer que se deshabilite la opción de adoptar (es decir, el botón), pero yo como usuario quiero poder estar seguro que se cargó ok mi mascota y ver en qué lugar queda, etc.
(por ejemplo, en Mercado libre yo puedo ver las cosas que yo publico)

**Comment by nicodiaz55** [comment]
Y como probamos que se subió? O sea, tiene sentido lo que decis, para mi habría que tener en la futura pantalla de perfil de usuario, cuales son las mascotas que vos subiste y demás. Pero no da implementar eso ahora. Diría dejar que se muestren y en todo caso decir luego que se va a hacer de esa otra forma.
