### ISSUE TITLE
Añadir Mascota - Falta botón para volver atrás

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#57]
Agregar un botón con flechita para regresar o un cancelar o similar (solo se está pudiendo volver a atrás con el botón físico del teléfono)

**Comment by nicodiaz55** [comment]
No voy a poner la flechita para atras porque ese evento no lo puedo capturar (no se como hacerlo, capaz se pueda), y entonces nunca ejecutaría el cartelito de "vas a perder los cambios". Por el momento voy a meter un botón arriba que diga "cerrar" como el de detalle de mascota.
