### ISSUE TITLE
Añadir Mascota - Ocultar ícono cuando se sube una imagen

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#62]
El ícono verde del fondo no se está ocultando cuando se sube la imagen y queda incompleto (lo tapa a medias la imagen subida).
Se deberia ocultar el ícono cuando se sube la imagen

**Comment by nicodiaz55** [comment]
Veo si puedo implementar el cardview con carrusel ahí. Y de paso sirve para poner más imagenes.
