### ISSUE TITLE
Detalle Mascota - Botón de Adopción

### ISSUE THREAD

**Issue by jennywoites** [jennywoites/TallerProyectosII-2C-2015#67]
Se debe agregar un botón para adoptar a la mascota. Este botón debe estar deshabilitado por el momento.

**Comment by nicodiaz55** [comment]
Ya existe... Es el botón del corazón.

**Comment by jennywoites** [comment]
Ok, habria que dejarlo desactivado entonces o que muestre un mensaje de que no está implementada la funcionalidad

**Comment by nicodiaz55** [comment]
Ok hago que tire un toast
