### ISSUE TITLE
3.3.1 - Servicio para solicitar la adopción de una mascota

### ISSUE THREAD

**Issue by ramirodoi** [jennywoites/TallerProyectosII-2C-2015#92]
Se debe poder registrar la mascota al usuario como pendiente de aprobación y agregarse el usuario a la lista de posibles adoptantes de quien la publicó.

**Comment by nicodiaz55** [comment]
Falta implementar:
- [x] Al hacer click en Aceptar guardar la solicitud para la mascota actual (el texto y el usuario que lo hizo, junto con la fecha). (en SolicitarAdopcionActivity.java)
- [x] Hacer una query en solicitudes para obtener las solicitudes recibidas para la mascota (en MascotaAdopcionPublicadaDetalleSolicitudesFragment.java)
- [x] Comprobar cuando se inicia la activity de detalle, si el usuario actual ya habia enviado una solicitud de adopcion (para deshabilitar el boton de adoptar). (en MascotaDetalleActivity.java)
